Fix missing file extension
The missing "wav" extension makes Freeswitch looking for .PCMU file, which does not exist. This is the error in the logfile:
d3b2a1d5-9dab-4067-b4a9-0296d6072ed6 2016-07-23 11:28:59.299530 [DEBUG] switch_ivr_play_say.c:1910 done playing file file_string://digits/1.wav!digits/1.wav!digits/3.wav!digits/0.wav 
d3b2a1d5-9dab-4067-b4a9-0296d6072ed6 2016-07-23 11:28:59.299530 [DEBUG] switch_ivr_play_say.c:70 No language specified - Using [en] 
d3b2a1d5-9dab-4067-b4a9-0296d6072ed6 2016-07-23 11:28:59.299530 [DEBUG] switch_ivr_play_say.c:250 Handle execute:[sleep(750)] (en:en) 
d3b2a1d5-9dab-4067-b4a9-0296d6072ed6 2016-07-23 11:29:00.159531 [DEBUG] switch_ivr_play_say.c:250 Handle play-file:[ivr/ivr-to_accept_press] (en:en) 
2016-07-23 11:29:00.159531 [ERR] mod_native_file.c:74 Error opening /usr/local/freeswitch/sounds/en/us/callie/ivr/ivr-to_accept_press.PCMU 
d3b2a1d5-9dab-4067-b4a9-0296d6072ed6 2016-07-23 11:29:00.279530 [DEBUG] switch_ivr_play_say.c:70 No language specified - Using [en] 
d3b2a1d5-9dab-4067-b4a9-0296d6072ed6 2016-07-23 11:29:00.279530 [DEBUG] switch_ivr_play_say.c:250 Handle execute:[sleep(750)] (en:en) 
d3b2a1d5-9dab-4067-b4a9-0296d6072ed6 2016-07-23 11:29:01.159532 [DEBUG] switch_ivr_play_say.c:250 Handle play-file:[ivr/ivr-to_accept_press] (en:en) 
2016-07-23 11:29:01.159532 [ERR] mod_native_file.c:74 Error opening /usr/local/freeswitch/sounds/en/us/callie/ivr/ivr-to_accept_press.PCMU 
d3b2a1d5-9dab-4067-b4a9-0296d6072ed6 2016-07-23 11:29:01.279530 [DEBUG] switch_ivr_play_say.c:70 No language specified - Using [en] 
d3b2a1d5-9dab-4067-b4a9-0296d6072ed6 2016-07-23 11:29:01.279530 [DEBUG] switch_ivr_play_say.c:250 Handle execute:[sleep(750)] (en:en) 
d3b2a1d5-9dab-4067-b4a9-0296d6072ed6 2016-07-23 11:29:02.179543 [DEBUG] switch_ivr_play_say.c:250 Handle play-file:[ivr/ivr-to_accept_press] (en:en) 
2016-07-23 11:29:02.179543 [ERR] mod_native_file.c:74 Error opening /usr/local/freeswitch/sounds/en/us/callie/ivr/ivr-to_accept_press.PCMU